table: cdc

TITLE:     Top 25 Retweets mentioning @CDCGov or @CDCEmergency

SUBHEADER: Diffusion of the top 25 most retweeted tweets with '@CDCGov' or '@CDCEmergency' since mid-March

EXTRA: The top 25 most retweeted tweets since March 17, 2020 with the terms <code>@CDCGov</code> or <code>@CDCEmergency</code>

JSON:      data/cdc-keyword.json

topN:      25

data       : /home/jupyter/data/diffusion/cdc_top_25_retweeted

output     : docs/cdc-keyword.html