table: cdc_userstreams

TITLE:     Top 25 Retweets of Center for Disease Control

SUBHEADER: Diffusion of the top 10 most retweeted @CDCGov, @CDCEmergency, @CDCEspañol, @CDCGlobal, @CDC_ehealth tweets since mid-April

JSON:      data/cdc.json

topN:      25

data       : /home/jupyter/data/diffusion/cdc_userstreams_top_25_retweeted

output     : docs/cdc.html