table: cdc_userstreams

TITLE:     Retweets of Center for Disease Control (CDC)

SUBHEADER: Diffusion of all retweeted @CDCGov, @CDCEmergency, @CDCEspañol, @CDCGlobal, @CDC_ehealth tweets since mid-April

JSON:      data/cdc-all.json

topN:      2000

data       : /home/jupyter/data/diffusion/cdc_userstreams_top_2000_retweeted

output     : docs/cdc-all.html