table: 'covid_data_representations'

TITLE:     Top 25 Retweets about covid & data

SUBHEADER: Diffusion of the top 25 most retweets with covid + data keywords

JSON:      data/covid-data.json

topN: 25
data       : /home/jupyter/data/diffusion/covid-data_top_25_retweeted

output     : docs/covid-data.html