table: 'covid_maps'
start: '2020-03-30 15:22:49 UTC' #beginning of cdc_userstreams collection

TITLE:     Top 25 Retweets about covid maps

SUBHEADER: Diffusion of the top 25 most retweets with covid + map keywords

JSON:      data/covid-maps.json

data       : /home/jupyter/data/diffusion/covid-maps_top_25_retweeted

output     : docs/covid-maps.html