table: 'covid_charts_and_graphics'

TITLE:     Top 25 Retweets about covid & charts

SUBHEADER: Diffusion of the top 25 most retweets with covid + charts/graphics keywords

JSON:      data/covid-charts.json

topN:      25

data       : /home/jupyter/data/diffusion/covid-charts_top_25_retweeted

output     : docs/covid-charts.html