table: obama

TITLE:     Top 25 Retweets of Barack Obama

SUBHEADER: Diffusion of the top 25 most retweeted tweets from Obama.

JSON:      data/obama.json

topN:      25

data       : /home/jupyter/data/diffusion/obama_top_25_retweeted

output     : docs/obama.html