table: world_health_organization

TITLE:     Top 25 Retweets of @WHO
SUBHEADER: Diffusion of the top 25 most retweeted tweets from the World Health Organization since mid-April
JSON:      data/who.json

topN       : 25

data       : /home/jupyter/data/diffusion/who_top_25_retweeted
output     : docs/who.html